# Generated by Django 3.1.3 on 2020-11-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='movie/')),
                ('title', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=100)),
                ('movie_type', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('res_date', models.DateField(null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
